{% set name = "pypng" %}
{% set version = "0.20220715.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 739c433ba96f078315de54c0db975aee537cbc3e1d0ae4ed9aab0ca1e427e2c1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - png

about:
  home: https://github.com/drj11/pypng/
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Pure Python PNG image encoder/decoder

extra:
  recipe-maintainers:
    - hmaarrfk
